# Generated by Django 5.1.1 on 2024-09-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
